#  Neobundle.toml

[[plugins]]
repo = 'Shougo/tabpagebuffer.vim'
on_if = 'tabpagenr() > 1'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_if = 1

# lets you use visual blocks like visual blockwise
# e.g. vapATEXT" will append the work "TEXT" at the end of
# each line in the "ap" region
#
[[plugins]]
repo = 'kana/vim-niceblock'
mappings = '<Plug>'

[[plugins]]
repo = 'Shougo/echodoc.vim'
on_i = 1
hook_source = 'let g:echodoc_enable_at_startup = 1'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]] # use xdg-open to open a url
repo = 'tyru/open-browser.vim'
functions = 'openbrowser#open'

# nice plugin for selecting windows
[[plugins]]
repo = 'andsild/vim-choosewin'
on_map = [['n', '<Plug>']]

# Operators
[[plugins]]
repo = 'kana/vim-operator-user'
functions = 'operator#user#define'

[[plugins]]
repo = 'kana/vim-operator-replace'
depends = 'vim-operator-user'
mappings = [['nx', '<Plug>(operator-replace)']]

# Use "sa" to highlight a region, and surround the region
# e.g. "saaW("
[[plugins]]
repo = 'rhysd/vim-operator-surround'
depends = 'vim-operator-user'
mappings = '<Plug>'

# Concealing in vim is to replace text with unicode symbols.
# eg. instead of "&&" you put "⋀".
# the plugin below allows you to put the cursor over the unicode symbol,
# but still copy the original "&&" instead of the concealment ("⋀")
[[plugins]]
repo = 'chikatoike/concealedyank.vim'
mappings = [['x', '<Plug>(operator-concealedyank)']]

# Textobjs. Clever API for creating blocks. like "at" for selecting "a time"
# if you want
[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'osyo-manga/vim-textobj-multiblock'
depends = 'vim-textobj-user'
mappings = [['ox', '<Plug>']]

[[plugins]] # for creating notes in rst format
repo = 'Rykka/riv.vim'
on_ft = 'rst'

[[plugins]] # markdown preview
repo = 'kannokanno/previm'
on_ft = ['markdown', 'rst', 'mkd']
depends = 'open-browser.vim'

[[plugins]] # vim tests in API
repo = 'thinca/vim-themis'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'


# The command that executes when you type "S" in vim. really nice
# quickjump to a text on your screen (typing in a few keys highlights all matches)
[[plugins]]
repo = 't9md/vim-smalls'
mappings = ['<Plug>(smalls)', '<Plug>(smalls-)']

[[plugins]] # wmii-ish window/tiling manager
repo = 'andsild/suckless.vim.git'

[[plugins]] # use vim's conceal features in python
repo = 'https://github.com/ehamberg/vim-cute-python.git'
on_ft = 'python'

[[plugins]] # nice keybindings
repo = 'https://github.com/andsild/vim-unimpaired.git'

[[plugins]]
repo = 'https://github.com/suan/vim-instant-markdown.git'
on_ft = 'markdown'

[[plugins]]
repo = 'Shougo/neoinclude.vim'
insert = 1

[[plugins]]
repo = 'https://github.com/rhysd/committia.vim.git'

[[plugins]]
repo = 'https://github.com/andsild/fzf.git'

[[plugins]]
repo = 'Shougo/neco-syntax'
insert = 1

[[plugins]]
repo = 'https://github.com/mhinz/vim-grepper.git'

[[plugins]]
repo = 'https://github.com/janko-m/vim-test.git'

[[plugins]]
repo = 'andsild/peskcolor.vim.git'

[[plugins]]
repo = 'andsild/missing-spellfiles-neovim.git'

[[plugins]]
repo = 'marijnh/tern_for_vim'
on_ft = ['javascript', 'javascript.jsx']
build = 'npm install'

[[plugins]] # colorscheme
repo = 'https://github.com/vim-scripts/mayansmoke.git'

[[plugins]] # show yank history
repo = 'https://github.com/Shougo/neoyank.vim.git'
on_if = 'has("clipboard")'

[[plugins]]
repo = 'https://github.com/parsonsmatt/intero-neovim.git'
on_ft = 'haskell'

[[plugins]]
repo = 'https://github.com/Shougo/denite.nvim'

[[plugins]]
repo = 'chemzqm/denite-git'

[[plugins]]
repo = 'https://github.com/chemzqm/denite-extra'

[[plugins]]
repo = 'bazelbuild/vim-bazel'
depends = 'vim-maktaba'

[[plugins]]
repo = 'https://github.com/reedes/vim-wordy'

[[plugins]]
repo = 'https://github.com/vim-scripts/Improved-AnsiEsc'

[[plugins]]
repo = 'https://github.com/itchyny/vim-gitbranch'
